name: gradle
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1.3.3
      with:
        arguments: build

